'use client';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import CssBaseline from '@mui/material/CssBaseline';
import { Button } from '@mui/material';
import './globals.css'
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import { SessionProvider } from 'next-auth/react';


export default function LayoutRoot({children}) {
  return (
    <html>
      <body>
        <SessionProvider>
        {children}
        </SessionProvider>
      </body>
    </html>

  )
}

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'OfficeMate',
  description: 'Generated by create next app',
}

// export default function RootLayout({
//   children, session
// }: {
//   children: React.ReactNode,
//   session
// }) {


//   return (
//     <SessionProvider session={session} >
//     <html lang="en">
//       <CssBaseline enableColorScheme />
//         <body className={inter.className}>{children}</body>
//     </html>
//     </SessionProvider>
//   )
// }
