import type { Metadata } from 'next'
import './globals.css'
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import { SessionProvider } from 'next-auth/react';
import ThemeProvider from './themes';


export default function LayoutRoot({ children }) {
  return (
    <ThemeProvider >
      <html>
        <body>
          <SessionProvider>
            {children}
          </SessionProvider>
        </body>
      </html>
     </ThemeProvider>
  )
}

export const metadata: Metadata = {
  title: 'OfficeMate',
  description: 'Generated by create next app',
}
